/**
 * DO NOT EDIT.  This file was generated by Closurizer, which read a
 * targets_cb.py file for instructions.
 */

goog.provide('cw.net.breaker_FlashConnector_swf');

cw.net.breaker_FlashConnector_swf = '0bd7d80e82723ab4b0dbc196a1ac15c5';
